name: Label Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened, edited, milestoned]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Label PR
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml

      - name: Add Type Label
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.pull_request?.title || context.payload.issue?.title;
            const body = context.payload.pull_request?.body || context.payload.issue?.body;
            const content = `${title}\n${body}`.toLowerCase();
            
            let typeLabel = '';
            
            if (content.includes('bug') || content.includes('fix')) {
              typeLabel = 'bug';
            } else if (content.includes('feat') || content.includes('feature')) {
              typeLabel = 'enhancement';
            } else if (content.includes('doc') || content.includes('docs')) {
              typeLabel = 'documentation';
            } else if (content.includes('refactor')) {
              typeLabel = 'refactor';
            }
            
            if (typeLabel) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [typeLabel]
              });
            } 